### ISSUE TITLE
No module called GatEngine

### ISSUE THREAD

**Issue by foriin** [AndreasHeger/gat#12]
Whatever I do, however I install and reinstall gat, I can't launch gat-compare:
```
Traceback (most recent call last):
  File "/home/adc34/anaconda2/bin/gat-compare.py", line 4, in <module>
    __import__('pkg_resources').run_script('gat==1.3.5', 'gat-compare.py')
  File "/home/adc34/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/adc34/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/home/adc34/anaconda2/lib/python2.7/site-packages/gat-1.3.5-py2.7-linux-x86_64.egg/EGG-INFO/scripts/gat-compare.py", line 98, in <module>
    import GatEngine
ImportError: No module named GatEngine
```

The frustration is overwhelming

**Comment by foriin** [comment]
Got it. You need manually change the line "import GatEngine"  to "import gat.Engine as GatEngine".
The same applies to SegmentList in gat-great.py.

**Comment by AndreasHeger** [comment]
Apologies for the late reply, @foriin , I have now finally fixed it.
