### ISSUE TITLE
Minor issue: GAT hangs for missing IDs in isochore files

### ISSUE THREAD

**Issue by skiaphrene** [AndreasHeger/gat#4]
Dear Andreas,

I've come across a minor issue while using GAT over the past months.

For some reason if the ID field (4th column) of the Isochores BED file is set to ".", GAT hangs with the following Python error:

```
Traceback (most recent call last):
  File "/software/UHTS/Analysis/gat/1.2/bin/gat-run.py", line 335, in <module>
    sys.exit(main(sys.argv))
  File "/software/UHTS/Analysis/gat/1.2/bin/gat-run.py", line 313, in main
    annotator_results = fromSegments(options, args)
  File "/software/UHTS/Analysis/gat/1.2/bin/gat-run.py", line 242, in fromSegments
    num_threads=options.num_threads)
  File "/software/UHTS/Analysis/gat/1.2/lib64/python2.7/site-packages/gat/__init__.py", line 915, in run
    track, counts, counters, segs, annotations, workspace, outfiles)
  File "/software/UHTS/Analysis/gat/1.2/lib64/python2.7/site-packages/gat/__init__.py", line 622, in sample
    contig_annotations.fromIsochores()
  File "GatEngine.pyx", line 2979, in GatEngine.IntervalCollection.fromIsochores (GatEngine/GatEngine.c:36284)
  File "GatEngine.pyx", line 2767, in GatEngine.IntervalDictionary.fromIsochores (GatEngine/GatEngine.c:32377)
ValueError: too many values to unpack (expected 2)
```

It runs fine if the "." is set to some other constant (e.g. "isoc" for isochore).
This is not the case for the workspace BED file: "ws" or "." both work just fine.

It actually took me a while to find the source of this problem, so I just thought I'd point it our here!

Best regards,

-- Alex

**Comment by AndreasHeger** [comment]
Thanks, I will take a look.

**Comment by rdalbanus** [comment]
Is there any specification for the isochore file format? Right now I'm using a single BED4 file with the isochore groups in the 4th column (e.g. gc_quintile_1, gc_quintile_2) and getting the same error as above. Should I be using a separate file for each isochore group, or maybe have the actual numeric for the whatever metric I'm "isochoring" with - say, having the GC content in the 4th column as an integer from 0-100? 
This is definitely worth expanding in the official documentation.
