### ISSUE TITLE
 dictionary changed size during iteration in Python 3

### ISSUE THREAD

**Issue by C-Garnett** [AndreasHeger/gat#7]
Hi Andreas,

Sorry to bother you again!

We are trying to run GAT in python 3 on the CGAT cluster - it works for this pair of files in python 2 but in python 3 we get this error:

```
gat-run.py --segment-file=/ifs/projects/proj060/genomic_context_2/annotations/all_enhancers.bed    --annotation-file=/ifs/projects/proj060/genomic_context_2/res/score5.bed --workspace-file=contigs.bed.gz > merged_no_IDR_vs_all_ensembl_exons.tsv
Traceback (most recent call last):
  File "/ifs/devel/catherineg/py35-v1/conda/bin/gat-run.py", line 4, in <module>
    __import__('pkg_resources').run_script('gat==1.3.3', 'gat-run.py')
  File "/ifs/devel/catherineg/py35-v1/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/ifs/devel/catherineg/py35-v1/conda/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/ifs/devel/catherineg/py35-v1/conda/lib/python3.5/site-packages/gat-1.3.3-py3.5-linux-x86_64.egg-info/scripts/gat-run.py", line 317, in <module>
    sys.exit(main(sys.argv))
  File "/ifs/devel/catherineg/py35-v1/conda/lib/python3.5/site-packages/gat-1.3.3-py3.5-linux-x86_64.egg-info/scripts/gat-run.py", line 295, in main
    annotator_results = fromSegments(options, args)
  File "/ifs/devel/catherineg/py35-v1/conda/lib/python3.5/site-packages/gat-1.3.3-py3.5-linux-x86_64.egg-info/scripts/gat-run.py", line 116, in fromSegments
    restrict_workspace=options.restrict_workspace)
  File "/ifs/devel/catherineg/py35-v1/conda/lib/python3.5/site-packages/gat/IO.py", line 246, in applyIsochores
    segments.filter(workspaces["collapsed"])
  File "gat/Engine.pyx", line 3051, in gat.Engine.IntervalCollection.filter (gat/Engine.c:44856)
RuntimeError: dictionary changed size during iteration
```

We have version 1.3.3 I think, which conda thinks is the latest version (although on github there is a 1.3.4).

Thanks very much,
Katy (and Catherine)

**Comment by AndreasHeger** [comment]
Thanks, I think I have fixed it now. I have pushed version 1.3.5. If the tests pass, I will release.

**Comment by AndreasHeger** [comment]
I have uploaded a new package to pypi. I have not built a new conda package yet, not sure if I manage to do before I leave.

@sebastian-luna-valero, could you help building one? Otherwise, a temporary fix is to install via pip:
```
pip install --upgrade gat
```

**Comment by sebastian-luna-valero** [comment]
Thanks All.

I am now updating the conda package for gat here:
https://github.com/bioconda/bioconda-recipes/pull/5426

Will let you know when it is available.

FYI: @KatyBrown

**Comment by sebastian-luna-valero** [comment]
Hello,

**Comment by sebastian-luna-valero** [comment]
Hello,

the `gat` package has been updated in conda. Please do `conda update gat` on your `py35-v1` environment to install the latest version.

Best regards,
Sebastian
